Repository Kernel360/KDEV4-HouseHub-BE, pull requests merged in 2025-05, with the labels that each got.

#186 youngseok, feat: 고객 태그 매핑 구현 + 고객 수정 등록 api 수정
  src/main/java/com/househub/backend/domain/crawlingProperty/controller/TagController.java
  src/main/java/com/househub/backend/domain/crawlingProperty/dto/TagResDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/entity/Tag.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/CrawlingTagService.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/TagService.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/TagServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerResDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/entity/CustomerTagMap.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerTagMapRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerStore.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
Labels: Feature

#188 고객 태그 리팩토링
  src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyResDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyTagResDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/entity/CrawlingPropertyTagMap.java
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryImpl.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/TagService.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/CrawlingPropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerResDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/entity/CustomerTagMap.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerTagMapRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerExecutor.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerStore.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerTagMapStore.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerTagMapStoreImpl.java
  src/main/java/com/househub/backend/domain/inquiry/repository/InquiryRepository.java
  src/main/java/com/househub/backend/domain/tag/controller/TagController.java
  src/main/java/com/househub/backend/domain/tag/dto/TagResDto.java
  src/main/java/com/househub/backend/domain/tag/entity/Tag.java
  src/main/java/com/househub/backend/domain/tag/repository/TagRepository.java
  src/main/java/com/househub/backend/domain/tag/service/TagExecutor.java
  src/main/java/com/househub/backend/domain/tag/service/TagReader.java
  src/main/java/com/househub/backend/domain/tag/service/TagService.java
  src/main/java/com/househub/backend/domain/tag/service/TagStore.java
  src/main/java/com/househub/backend/domain/tag/service/impl/TagExecutorImpl.java
  src/main/java/com/househub/backend/domain/tag/service/impl/TagReaderImpl.java
  src/main/java/com/househub/backend/domain/tag/service/impl/TagServiceImpl.java
  src/main/java/com/househub/backend/domain/tag/service/impl/TagStoreImpl.java
Labels: Refactor

#185 seongeun, feat: 매물 등록 시, 계약 정보도 함께 등록하도록 수정 #182
  src/main/java/com/househub/backend/domain/contract/dto/BasicContractDto.java
  src/main/java/com/househub/backend/domain/property/dto/CreatePropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
Labels: Feature

#194 youngseok, feat: 공인중개사 정보 수정 API 구현 + Redis serialVersionUID 문제 해결 + …
  src/main/java/com/househub/backend/common/config/RedisConfig.java
  src/main/java/com/househub/backend/common/util/SecurityUtil.java
  src/main/java/com/househub/backend/domain/agent/AgentReader.java
  src/main/java/com/househub/backend/domain/agent/controller/AgentController.java
  src/main/java/com/househub/backend/domain/agent/dto/AgentResDto.java
  src/main/java/com/househub/backend/domain/agent/dto/GetMyInfoResDto.java
  src/main/java/com/househub/backend/domain/agent/dto/UpdateAgentReqDto.java
  src/main/java/com/househub/backend/domain/agent/entity/Agent.java
  src/main/java/com/househub/backend/domain/agent/enums/AgentStatus.java
  src/main/java/com/househub/backend/domain/agent/enums/Role.java
  src/main/java/com/househub/backend/domain/agent/repository/AgentRepository.java
  src/main/java/com/househub/backend/domain/agent/service/AgentReader.java
  src/main/java/com/househub/backend/domain/agent/service/AgentService.java
  src/main/java/com/househub/backend/domain/agent/service/impl/AgentReaderImpl.java
  src/main/java/com/househub/backend/domain/agent/service/impl/AgentServiceImpl.java
  src/main/java/com/househub/backend/domain/auth/dto/CustomAgentDetails.java
  src/main/java/com/househub/backend/domain/auth/dto/GetSessionResDto.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/job/SmsJobScheduler.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
  src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
Labels: Bug, Feature

#191 월 별 만료 예정 계약 목록 조회 API 구현
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/contract/dto/ExpiringContractItemResDto.java
  src/main/java/com/househub/backend/domain/contract/dto/ExpiringContractListResDto.java
  src/main/java/com/househub/backend/domain/contract/enums/ContractType.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/dashboard/controller/DashboardController.java
  src/main/java/com/househub/backend/domain/dashboard/service/DashboardService.java
  src/main/java/com/househub/backend/domain/dashboard/service/impl/DashboardServiceImpl.java
Labels: Feature

#195 seongeun, feat: 매물 태그 구현
  src/main/java/com/househub/backend/common/config/SwaggerConfig.java
  src/main/java/com/househub/backend/domain/property/dto/CreatePropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/UpdatePropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/entity/PropertyTagMap.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyTagMapRepository.java
  src/main/java/com/househub/backend/domain/property/service/PropertyStore.java
  src/main/java/com/househub/backend/domain/property/service/PropertyTagMapStore.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyStoreImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyTagMapStoreImpl.java
Labels: Feature

#201 seongeun, refactor: 매물 및 계약 리팩토링 + 대시보드 API 구현
  src/main/java/com/househub/backend/domain/contract/controller/ContractController.java
  src/main/java/com/househub/backend/domain/contract/dto/BasicContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractSummaryResDto.java
  src/main/java/com/househub/backend/domain/contract/dto/CreateContractResDto.java
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/contract/service/ContractReader.java
  src/main/java/com/househub/backend/domain/contract/service/ContractService.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractReaderImpl.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/contract/validator/ContractValidator.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerSummaryResDto.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerReader.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/property/controller/PropertyController.java
  src/main/java/com/househub/backend/domain/property/dto/CreatePropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertySummaryResDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/service/PropertyReader.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyReaderImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/property/validator/PropertyValidator.java
Labels: Feature, Refactor

#207 fix: SSE 알림이 알림 저장 완료 전에 트리거되어 null 또는 오류 해결 #206
  src/main/java/com/househub/backend/domain/inquiry/dto/InquiryDetailResDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/InquiryTemplateSharedResDto.java
  src/main/java/com/househub/backend/domain/notification/service/EmailService.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationService.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NotificationExecutorImpl.java
Labels: Bug

#210 byungchan, fix: 공개 매물 조회 버그 해결 #209
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryImpl.java
Labels: Bug

#212 youngseok, 고객 상세 페이지에 추천 매물 정보 추가
  src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java
  src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyResDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepository.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/CrawlingPropertyService.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/CrawlingPropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/main/java/com/househub/backend/domain/property/service/PropertyReader.java
  src/main/java/com/househub/backend/domain/property/service/PropertyService.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyReaderImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
Labels: Feature

#218 비밀번호 재설정 시 필요한 API 구현 및 이메일 전송 서비스 및 콘텐츠 제공 구조 추상화
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/agent/entity/Agent.java
  src/main/java/com/househub/backend/domain/agent/repository/AgentRepository.java
  src/main/java/com/househub/backend/domain/agent/service/AgentReader.java
  src/main/java/com/househub/backend/domain/agent/service/impl/AgentReaderImpl.java
  src/main/java/com/househub/backend/domain/auth/controller/AuthController.java
  src/main/java/com/househub/backend/domain/auth/dto/ResetPasswordReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/SendEmailReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/ValidateTokenReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/ValidateTokenResDto.java
  src/main/java/com/househub/backend/domain/auth/enums/TokenType.java
  src/main/java/com/househub/backend/domain/auth/service/AuthCode.java
  src/main/java/com/househub/backend/domain/auth/service/EmailAuthCodeManager.java
  src/main/java/com/househub/backend/domain/auth/service/EmailVerificationService.java
  src/main/java/com/househub/backend/domain/auth/service/PasswordResetService.java
  src/main/java/com/househub/backend/domain/auth/service/PasswordResetTokenManager.java
  src/main/java/com/househub/backend/domain/auth/service/TokenValidateService.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthCodeImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/EmailAuthCodeManagerImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/TokenValidateServiceImpl.java
  src/main/java/com/househub/backend/domain/notification/dto/EmailReqDto.java
  src/main/java/com/househub/backend/domain/notification/service/EmailContentProvider.java
  src/main/java/com/househub/backend/domain/notification/service/EmailService.java
  src/main/java/com/househub/backend/domain/notification/service/impl/EmailVerificationContentProvider.java
  src/main/java/com/househub/backend/domain/notification/service/impl/PasswordResetEmailContentProvider.java
Labels: Feature

#219 최종 발표 전 3차 배포
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/agent/entity/Agent.java
  src/main/java/com/househub/backend/domain/agent/repository/AgentRepository.java
  src/main/java/com/househub/backend/domain/agent/service/AgentReader.java
  src/main/java/com/househub/backend/domain/agent/service/impl/AgentReaderImpl.java
  src/main/java/com/househub/backend/domain/auth/controller/AuthController.java
  src/main/java/com/househub/backend/domain/auth/dto/ResetPasswordReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/SendEmailReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/ValidateTokenReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/ValidateTokenResDto.java
  src/main/java/com/househub/backend/domain/auth/enums/TokenType.java
  src/main/java/com/househub/backend/domain/auth/service/AuthCode.java
  src/main/java/com/househub/backend/domain/auth/service/EmailAuthCodeManager.java
  src/main/java/com/househub/backend/domain/auth/service/EmailVerificationService.java
  src/main/java/com/househub/backend/domain/auth/service/PasswordResetService.java
  src/main/java/com/househub/backend/domain/auth/service/PasswordResetTokenManager.java
  src/main/java/com/househub/backend/domain/auth/service/TokenValidateService.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthCodeImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/EmailAuthCodeManagerImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/TokenValidateServiceImpl.java
  src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyResDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepository.java
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryImpl.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/CrawlingPropertyService.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/CrawlingPropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/notification/dto/EmailReqDto.java
  src/main/java/com/househub/backend/domain/notification/service/EmailContentProvider.java
  src/main/java/com/househub/backend/domain/notification/service/EmailService.java
  src/main/java/com/househub/backend/domain/notification/service/impl/EmailVerificationContentProvider.java
  src/main/java/com/househub/backend/domain/notification/service/impl/PasswordResetEmailContentProvider.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertySearchDto.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepositoryCustomImpl.java
  src/main/java/com/househub/backend/domain/property/service/PropertyReader.java
  src/main/java/com/househub/backend/domain/property/service/PropertyService.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyReaderImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
Labels: Chore

#221 지역(Region) 엔티티 변경 및 계층형 행정구역 목록 조회 API 구현
  src/main/java/com/househub/backend/HouseHubBackendApplication.java
  src/main/java/com/househub/backend/domain/agent/dto/AgentResDto.java
  src/main/java/com/househub/backend/domain/agent/enums/AgentStatus.java
  src/main/java/com/househub/backend/domain/agent/enums/Role.java
  src/main/java/com/househub/backend/domain/auth/dto/CustomAgentDetails.java
  src/main/java/com/househub/backend/domain/region/controller/RegionController.java
  src/main/java/com/househub/backend/domain/region/dto/RegionDto.java
  src/main/java/com/househub/backend/domain/region/dto/RegionOptionDto.java
  src/main/java/com/househub/backend/domain/region/entity/Region.java
  src/main/java/com/househub/backend/domain/region/enums/RegionLevel.java
  src/main/java/com/househub/backend/domain/region/repository/RegionRepository.java
  src/main/java/com/househub/backend/domain/region/service/RegionCacheInitializer.java
  src/main/java/com/househub/backend/domain/region/service/RegionCsvImportService.java
  src/main/java/com/househub/backend/domain/region/service/RegionReadService.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
Labels: Feature

#222 최종 발표 전 4차 배포
  src/main/java/com/househub/backend/HouseHubBackendApplication.java
  src/main/java/com/househub/backend/domain/agent/dto/AgentResDto.java
  src/main/java/com/househub/backend/domain/agent/enums/AgentStatus.java
  src/main/java/com/househub/backend/domain/agent/enums/Role.java
  src/main/java/com/househub/backend/domain/auth/dto/CustomAgentDetails.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/CrawlingPropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerReader.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/region/controller/RegionController.java
  src/main/java/com/househub/backend/domain/region/dto/RegionDto.java
  src/main/java/com/househub/backend/domain/region/dto/RegionOptionDto.java
  src/main/java/com/househub/backend/domain/region/entity/Region.java
  src/main/java/com/househub/backend/domain/region/enums/RegionLevel.java
  src/main/java/com/househub/backend/domain/region/repository/RegionRepository.java
  src/main/java/com/househub/backend/domain/region/service/RegionCacheInitializer.java
  src/main/java/com/househub/backend/domain/region/service/RegionCsvImportService.java
  src/main/java/com/househub/backend/domain/region/service/RegionReadService.java
  src/main/java/com/househub/backend/domain/sms/service/impl/AligoGatewayImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsExecutorImpl.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
Labels: Chore

#224 fix: province=서울&city=마포구 에 해당하는 매물 목록 조회 안되는 버그 해결 #223
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryImpl.java
Labels: Bug

#226 fix: 고객 삭제시 발생하는 문제 해결
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/CrawlingPropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerReader.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsExecutorImpl.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerReaderImplTest.java
Labels: Bug

#233 fix: 이미 가입된 이메일의 경우 예외 처리 추가 #232
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/auth/service/EmailVerificationService.java
Labels: Bug

#234 최종 발표 전 6차 배포
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/auth/service/EmailVerificationService.java
Labels: Chore

#244 문의 생성 후 알림 전송 구조 개선 (AFTER_COMMIT & 이벤트 리스너 분리) #239
  src/main/java/com/househub/backend/common/config/AsyncConfig.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java
  src/main/java/com/househub/backend/domain/notification/controller/NotificationController.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryCreatedEvent.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryEmailListener.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationListener.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationReadyEvent.java
  src/main/java/com/househub/backend/domain/notification/event/InquirySseListener.java
  src/main/java/com/househub/backend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/househub/backend/domain/notification/service/EmailService.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationReader.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationService.java
  src/main/java/com/househub/backend/domain/notification/service/SseEmitterService.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NewInquiryCreatedContentProvider.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NotificationReaderImpl.java
Labels: Feature

#246 최종 발표 전 8차 배포
  src/main/java/com/househub/backend/common/config/AsyncConfig.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java
  src/main/java/com/househub/backend/domain/notification/controller/NotificationController.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryCreatedEvent.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryEmailListener.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationListener.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationReadyEvent.java
  src/main/java/com/househub/backend/domain/notification/event/InquirySseListener.java
  src/main/java/com/househub/backend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/househub/backend/domain/notification/service/EmailService.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationReader.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationService.java
  src/main/java/com/househub/backend/domain/notification/service/SseEmitterService.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NewInquiryCreatedContentProvider.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NotificationReaderImpl.java
Labels: Chore

#251 최종 발표 전 9차 배포
  src/main/java/com/househub/backend/domain/crawlingProperty/controller/CrawlingPropertyController.java
  src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyReqDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/dto/CrawlingPropertyTagResDto.java
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryCustom.java
  src/main/java/com/househub/backend/domain/crawlingProperty/repository/CrawlingPropertyRepositoryImpl.java
  src/main/java/com/househub/backend/domain/crawlingProperty/service/impl/CrawlingPropertyServiceImpl.java
Labels: Chore
