Repository Kernel360/KDEV4-HouseHub-BE, pull requests merged in 2025-04, with the labels that each got.

#55 youngseok, feat: coolsms에서 aligo로 전환+단건 전송+전송내역 조회+고객,공인중개사 연관관계 설정 #54
  build.gradle
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/househub/backend/domain/agent/entity/Agent.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/controller/SmsController.java
  src/main/java/com/househub/backend/domain/sms/dto/CreateUpdateTemplateReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/GetSmsHistoryReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SmsHistoryResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SmsResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/TemplateResDto.java
  src/main/java/com/househub/backend/domain/sms/entity/Sms.java
  src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java
  src/main/java/com/househub/backend/domain/sms/enums/Status.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/repository/TemplateRepository.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/AligoSmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/TemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/SmsService.java
  src/main/java/com/househub/backend/domain/sms/service/TemplateService.java
  src/main/java/com/househub/backend/domain/sms/utils/AligoApiClient.java
  src/main/java/com/househub/backend/domain/sms/utils/JacksonConfig.java
  src/main/java/com/househub/backend/domain/sms/utils/RestTemplateConfig.java
  src/test/java/com/househub/backend/domain/contract/controller/ContractControllerTest.java
Labels: Feature

#61 byungchan, feature: 공인중개사 인증 관련 API 구현 및 수정(회원가입, 로그인, 세션 조회, 내 정보 조회)
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/util/SessionManager.java
  src/main/java/com/househub/backend/domain/agent/controller/AgentController.java
  src/main/java/com/househub/backend/domain/agent/dto/GetMyInfoResDto.java
  src/main/java/com/househub/backend/domain/agent/service/AgentService.java
  src/main/java/com/househub/backend/domain/agent/service/impl/AgentServiceImpl.java
  src/main/java/com/househub/backend/domain/auth/controller/AuthController.java
  src/main/java/com/househub/backend/domain/auth/dto/GetSessionResDto.java
  src/main/java/com/househub/backend/domain/auth/dto/SignInReqDto.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
Labels: Feature

#59 youngseok, feat: 로그인한 agent 정보를 고객 등록 시 같이 저장 feat: update 함수 개선 youngseok, hotfix: stash 충돌 해결 #12
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
Labels: Feature

#58 youngseok, hotfix: 커밋메세지 검사기 개선(feature,fix 추가) + 메세지 길이 100자로 개선 #16
  commitlint.config.js
Labels: Chore

#57 seongeun, feat: 매물, 계약 검색 기능 구현 #52
  src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/househub/backend/domain/contract/controller/ContractController.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractSearchDto.java
  src/main/java/com/househub/backend/domain/contract/dto/CreateContractResDto.java
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/contract/service/ContractService.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/property/controller/PropertyController.java
  src/main/java/com/househub/backend/domain/property/dto/CreatePropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertySearchDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/main/java/com/househub/backend/domain/property/service/PropertyService.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
  src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
Labels: Feature

#64 byungchan, feature: 인증 메일 발송 API 응답 데이터 변경 및 merge conflict 해결
  Dockerfile
  build.gradle
  commitlint.config.js
  compose.yaml
  nginx/nginx.conf
  redis/redis.conf
  src/main/java/com/househub/backend/common/config/RedisConfig.java
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/househub/backend/domain/auth/controller/AuthController.java
  src/main/java/com/househub/backend/domain/auth/dto/SendEmailReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/SendEmailResDto.java
  src/main/java/com/househub/backend/domain/auth/dto/SignUpReqDto.java
  src/main/java/com/househub/backend/domain/auth/dto/VerifyEmailReqDto.java
  src/main/java/com/househub/backend/domain/auth/service/AuthCode.java
  src/main/java/com/househub/backend/domain/auth/service/AuthService.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthCodeImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/test/java/com/househub/backend/domain/auth/service/AgentSignUpServiceTest.java
Labels: Feature

#66 byungchan, feature: 실제 이메일 발송 로직 추가
  Dockerfile
  build.gradle
  compose.yaml
  src/main/java/com/househub/backend/common/config/RedisConfig.java
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/househub/backend/domain/agent/repository/AgentRepository.java
  src/main/java/com/househub/backend/domain/auth/controller/AuthController.java
  src/main/java/com/househub/backend/domain/auth/service/AuthService.java
  src/main/java/com/househub/backend/domain/auth/service/EmailService.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/EmailServiceImpl.java
Labels: Feature

#27 siyoon, hyunho, feat: 상담 crud 구현, 연관관계 수정, 테스트 코드 개선 및 리팩토링 #25
  src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationReqDto.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationResDto.java
  src/main/java/com/househub/backend/domain/consultation/entity/Consultation.java
  src/main/java/com/househub/backend/domain/consultation/enums/ConsultationStatus.java
  src/main/java/com/househub/backend/domain/consultation/enums/ConsultationType.java
  src/main/java/com/househub/backend/domain/consultation/repository/ConsultationRepository.java
  src/main/java/com/househub/backend/domain/consultation/service/ConsultationService.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
  src/test/java/com/househub/backend/domain/consultation/service/ConsultationServiceTest.java
Labels: Bug, Feature, Test

#70 youngseok, feat: Entity+DTO 변환 메소드에 id값 추가|고객 수정시 이메일 존재여부 확인 수정 | 스웨거에 엑셀 파일 입력 추가 #12 #69
  .gitignore
  build.gradle
  package-lock.json
  src/main/java/com/househub/backend/common/config/SwaggerConfig.java
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerResDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
Labels: Feature

#72 feat: sms+template dto 에서 부동산 정보를 id값으로 저장하게 만들기 + feat: sms 전체 조회, 단건 조회, 저장 구현 #54
  src/main/java/com/househub/backend/domain/sms/controller/SmsController.java
  src/main/java/com/househub/backend/domain/sms/dto/AligoHistoryReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/AligoHistoryResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/AligoSmsResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/TemplateResDto.java
  src/main/java/com/househub/backend/domain/sms/entity/Sms.java
  src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java
  src/main/java/com/househub/backend/domain/sms/enums/MessageType.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/AligoSmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/SmsService.java
Labels: Feature

#73 youngseok, feat: 알리고 api와 프론트 엔드의 dto 분할 #54
  src/main/java/com/househub/backend/domain/sms/dto/AligoHistoryResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/TemplateResDto.java
  src/main/java/com/househub/backend/domain/sms/entity/Sms.java
  src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/AligoSmsServiceImpl.java
Labels: Feature

#74 seongeun, feat: 계약 상세 조회 기능 구현 및 검색 기능 수정 #38 #52
  src/main/java/com/househub/backend/domain/contract/controller/ContractController.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/contract/service/ContractService.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
Labels: Feature

#75 siyoon, fix: 상담 기능 백엔드 버그 수정 #25
  build.gradle
  src/main/java/com/househub/backend/domain/auth/service/impl/EmailServiceImpl.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationResDto.java
Labels: Bug

#82 Dockerfile 빌드 에러 해결
  Dockerfile
Labels: Bug

#85 byungchan, fix: Gihub Actions deploy.yml applciation.yml 파일 누락된 변수 추가
  .github/workflows/deploy.yml
Labels: Bug

#86 byungchan, fix: Gihub Actions deploy.yml applciation.yml 파일 생성 로직 제거 #84
  .github/workflows/deploy.yml
Labels: Bug

#88 스웨거 접속 URL 에 대한 CORS 설정 허용
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
Labels: Bug

#89 fix: 프론트엔드 연동 시 CORS 에러 해결
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
Labels: Bug

#98 byungchan, feature: 고객 문의 목록 및 상세정보 조회 API 구현
  src/main/java/com/househub/backend/common/exception/BusinessException.java
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/househub/backend/domain/auth/service/impl/EmailServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/entity/CustomerCandidate.java
  src/main/java/com/househub/backend/domain/inquiry/controller/InquiryController.java
  src/main/java/com/househub/backend/domain/inquiry/dto/InquiryDetailResDto.java
  src/main/java/com/househub/backend/domain/inquiry/dto/InquiryListItemResDto.java
  src/main/java/com/househub/backend/domain/inquiry/dto/InquiryListResDto.java
  src/main/java/com/househub/backend/domain/inquiry/repository/InquiryRepository.java
  src/main/java/com/househub/backend/domain/inquiry/service/InquiryService.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java
Labels: Feature

#93 youngseok, feat: 고객 검색 기능 추가 #41
  src/main/java/com/househub/backend/common/dto/PaginationDto.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerListResDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerSearchDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
Labels: Feature

#97 seongeun, fix: 페이지네이션 수정 및 계약 enum 변경, 매물 정보 수정 시 고객도 수정 가능하도록 변경
  src/main/java/com/househub/backend/domain/contract/controller/ContractController.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/enums/ContractStatus.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/property/controller/PropertyController.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
  src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
Labels: Bug

#104 youngseok, feat: 고객 전체조회 관련 로직 수정 #103
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
Labels: Bug

#105 byungchan, feature: 대시보드에서 사용되는 통계 관련 데이터 API 구현
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/dashboard/controller/DashboardController.java
  src/main/java/com/househub/backend/domain/dashboard/dto/ChartDataResDto.java
  src/main/java/com/househub/backend/domain/dashboard/dto/DashboardStatsResDto.java
  src/main/java/com/househub/backend/domain/dashboard/dto/MultiDatasetChartResDto.java
  src/main/java/com/househub/backend/domain/dashboard/dto/PropertyTypeCount.java
  src/main/java/com/househub/backend/domain/dashboard/dto/RecentPropertyResDto.java
  src/main/java/com/househub/backend/domain/dashboard/service/DashboardService.java
  src/main/java/com/househub/backend/domain/dashboard/service/impl/DashboardServiceImpl.java
  src/main/java/com/househub/backend/domain/property/enums/PropertyType.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
Labels: Feature

#108 중간 발표 전 3차 배포
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/dashboard/controller/DashboardController.java
  src/main/java/com/househub/backend/domain/dashboard/dto/ChartDataResDto.java
  src/main/java/com/househub/backend/domain/dashboard/dto/DashboardStatsResDto.java
  src/main/java/com/househub/backend/domain/dashboard/dto/MultiDatasetChartResDto.java
  src/main/java/com/househub/backend/domain/dashboard/dto/PropertyTypeCount.java
  src/main/java/com/househub/backend/domain/dashboard/dto/RecentPropertyResDto.java
  src/main/java/com/househub/backend/domain/dashboard/service/DashboardService.java
  src/main/java/com/househub/backend/domain/dashboard/service/impl/DashboardServiceImpl.java
  src/main/java/com/househub/backend/domain/property/enums/PropertyType.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
Labels: Chore

#109 youngseok, feat: 문자|문자 템플릿 페이지네이션 + 검색 관련 백엔드 수정사항 #54
  src/main/java/com/househub/backend/domain/sms/controller/SmsController.java
  src/main/java/com/househub/backend/domain/sms/dto/CreateUpdateTemplateReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SmsListResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SmsTemplateListResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/TemplateResDto.java
  src/main/java/com/househub/backend/domain/sms/entity/Sms.java
  src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/repository/TemplateRepository.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/AligoSmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/TemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/SmsService.java
  src/main/java/com/househub/backend/domain/sms/service/TemplateService.java
Labels: Feature

#112 seongeun, fix: 계약 등록 시 동일 고객에 대한 예외 처리 및 계약 시작/종료일 예외 처리, 매물에 active 컬럼 추가
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
Labels: Bug

#116 seongeun, fix: 매물 active 상태에 따른 검색 필드 추가 및 테스트 코드 추가, 중개사 본인이 등록한 매물만 조회하도록 수정
  src/main/java/com/househub/backend/domain/property/controller/PropertyController.java
  src/main/java/com/househub/backend/domain/property/dto/PropertySearchDto.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/main/java/com/househub/backend/domain/property/service/PropertyService.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
Labels: Feature

#118 중간 발표 전 마지막 배포
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationResDto.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/dashboard/controller/DashboardController.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/InquiryTemplateResDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/repository/InquiryTemplateSharedTokenRepository.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/property/controller/PropertyController.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertySearchDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/main/java/com/househub/backend/domain/property/service/PropertyService.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/controller/SmsController.java
  src/main/java/com/househub/backend/domain/sms/dto/CreateUpdateTemplateReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SmsListResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SmsTemplateListResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/TemplateResDto.java
  src/main/java/com/househub/backend/domain/sms/entity/Sms.java
  src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/repository/TemplateRepository.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/AligoSmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/Impl/TemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/SmsService.java
  src/main/java/com/househub/backend/domain/sms/service/TemplateService.java
  src/test/java/com/househub/backend/domain/auth/service/AgentSignInServiceTest.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
  src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
Labels: Chore

#120 seongeun, fix: 매물 entity 및 dto 에 지번주소 추가
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
Labels: Bug

#123 중간발표 당일 배포
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
Labels: Chore

#127 상담 목록 조회 API 구현(검색, 필터, 페이지네이션 포함)
  src/main/java/com/househub/backend/HouseHubBackendApplication.java
  src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationListResDto.java
  src/main/java/com/househub/backend/domain/consultation/enums/ConsultationStatus.java
  src/main/java/com/househub/backend/domain/consultation/repository/ConsultationRepository.java
  src/main/java/com/househub/backend/domain/consultation/service/ConsultationService.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
  src/test/java/com/househub/backend/domain/consultation/service/ConsultationServiceTest.java
Labels: Feature

#128 상담 목록 조회 API 구현사항 배포 서버에 반영
  src/main/java/com/househub/backend/HouseHubBackendApplication.java
  src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationListResDto.java
  src/main/java/com/househub/backend/domain/consultation/enums/ConsultationStatus.java
  src/main/java/com/househub/backend/domain/consultation/repository/ConsultationRepository.java
  src/main/java/com/househub/backend/domain/consultation/service/ConsultationService.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
  src/test/java/com/househub/backend/domain/consultation/service/ConsultationServiceTest.java
Labels: Chore

#132 문의 등록, 문의 목록 조회, 문의 상세정보 조회 API 리팩토링
  commitlint.config.js
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/agent/dto/AgentResDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/enums/CustomerStatus.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerExecutor.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerReader.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerStore.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/inquiry/dto/CreateInquiryCommand.java
  src/main/java/com/househub/backend/domain/inquiry/dto/CreateInquiryReqDto.java
  src/main/java/com/househub/backend/domain/inquiry/dto/InquiryDetailResDto.java
  src/main/java/com/househub/backend/domain/inquiry/dto/InquiryListItemResDto.java
  src/main/java/com/househub/backend/domain/inquiry/entity/Inquiry.java
  src/main/java/com/househub/backend/domain/inquiry/repository/InquiryRepository.java
  src/main/java/com/househub/backend/domain/inquiry/service/InquiryExecutor.java
  src/main/java/com/househub/backend/domain/inquiry/service/InquiryReader.java
  src/main/java/com/househub/backend/domain/inquiry/service/InquiryStore.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryExecutorImpl.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryReaderImpl.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryStoreImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateReader.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateReaderImpl.java
Labels: Refactor

#131 younseok, fix: Customer 리팩토링(CustomerServiceImpl을 CustomerReader+…
  src/main/java/com/househub/backend/common/enums/Gender.java
  src/main/java/com/househub/backend/common/exception/EmailAlreadyExistsException.java
  src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/househub/backend/common/exception/InvalidExcelValueException.java
  src/main/java/com/househub/backend/common/exception/InvalidFormatException.java
  src/main/java/com/househub/backend/common/validation/ExcelValidator.java
  src/main/java/com/househub/backend/domain/agent/AgentReader.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationReqDto.java
  src/main/java/com/househub/backend/domain/consultation/entity/Consultation.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerSearchDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerExecutor.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerReader.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerStore.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/customer/util/CustomerExcelProcessor.java
  src/main/java/com/househub/backend/domain/customer/util/ExcelParserUtils.java
  src/main/java/com/househub/backend/domain/property/dto/PropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/AligoSmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/TemplateServiceImpl.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerReaderImplTest.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerServiceImplTest.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerStoreImplTest.java
Labels: Refactor

#135 youngseok, fix: 문자 + 문자 템플릿 리팩토링 #134
  src/main/java/com/househub/backend/domain/sms/controller/SmsController.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsResDto.java
  src/main/java/com/househub/backend/domain/sms/entity/Sms.java
  src/main/java/com/househub/backend/domain/sms/entity/SmsTemplate.java
  src/main/java/com/househub/backend/domain/sms/enums/SmsStatus.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/repository/TemplateRepository.java
  src/main/java/com/househub/backend/domain/sms/service/AligoService.java
  src/main/java/com/househub/backend/domain/sms/service/SmsReader.java
  src/main/java/com/househub/backend/domain/sms/service/SmsService.java
  src/main/java/com/househub/backend/domain/sms/service/SmsStore.java
  src/main/java/com/househub/backend/domain/sms/service/SmsTemplateExecutor.java
  src/main/java/com/househub/backend/domain/sms/service/SmsTemplateReader.java
  src/main/java/com/househub/backend/domain/sms/service/SmsTemplateService.java
  src/main/java/com/househub/backend/domain/sms/service/SmsTemplateStore.java
  src/main/java/com/househub/backend/domain/sms/service/impl/AligoServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/AligoSmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsReaderImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsSmsTemplateReaderImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsSmsTemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsSmsTemplateStoreImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsStoreImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsTemplateExecutorImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/TemplateServiceImpl.java
Labels: Refactor

#138 youngseok, fix: 엑셀 파일 용량 확인 추가 + 고객 엔티티 제약조건 수정 #129 #139
  src/main/java/com/househub/backend/common/config/SwaggerConfig.java
  src/main/java/com/househub/backend/common/validation/CustomerExcelValidator.java
  src/main/java/com/househub/backend/common/validation/ValidCustomerExcel.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/enums/CustomerExcelColumn.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/customer/util/CustomerExcelProcessor.java
  src/main/java/com/househub/backend/domain/customer/util/ExcelParserUtils.java
  src/test/java/com/househub/backend/domain/auth/service/AgentSignUpServiceTest.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerStoreImplTest.java
Labels: Refactor

#143 알림 생성, 목록 조회, 읽음/안읽음/삭제 처리 API 구현
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/agent/service/AgentReader.java
  src/main/java/com/househub/backend/domain/agent/service/impl/AgentReaderImpl.java
  src/main/java/com/househub/backend/domain/auth/controller/AuthController.java
  src/main/java/com/househub/backend/domain/auth/service/EmailService.java
  src/main/java/com/househub/backend/domain/inquiry/dto/InquiryListItemResDto.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateCreateExecutor.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateReader.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateStore.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateCreateExecutorImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateReaderImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateStoreImpl.java
  src/main/java/com/househub/backend/domain/notification/controller/NotificationController.java
  src/main/java/com/househub/backend/domain/notification/dto/NotificationDto.java
  src/main/java/com/househub/backend/domain/notification/dto/NotificationIdsReqDto.java
  src/main/java/com/househub/backend/domain/notification/dto/NotificationIdsResDto.java
  src/main/java/com/househub/backend/domain/notification/dto/NotificationListResDto.java
  src/main/java/com/househub/backend/domain/notification/entity/Notification.java
  src/main/java/com/househub/backend/domain/notification/enums/NotificationType.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryCreatedEvent.java
  src/main/java/com/househub/backend/domain/notification/event/InquiryNotificationListener.java
  src/main/java/com/househub/backend/domain/notification/repository/EmitterRepository.java
  src/main/java/com/househub/backend/domain/notification/repository/InMemoryEmitterRepository.java
  src/main/java/com/househub/backend/domain/notification/repository/NotificationRepository.java
  src/main/java/com/househub/backend/domain/notification/service/EmailService.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationExecutor.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationReader.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationService.java
  src/main/java/com/househub/backend/domain/notification/service/NotificationStore.java
  src/main/java/com/househub/backend/domain/notification/service/SseEmitterService.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NotificationExecutorImpl.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NotificationReaderImpl.java
  src/main/java/com/househub/backend/domain/notification/service/impl/NotificationStoreImpl.java
Labels: Feature

#148 seongeun, refactor: 매물, 계약 리팩토링
  .gitignore
  build.gradle
  src/main/java/com/househub/backend/common/config/QuerydslConfig.java
  src/main/java/com/househub/backend/domain/contract/controller/ContractController.java
  src/main/java/com/househub/backend/domain/contract/dto/CreateContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/contract/dto/UpdateContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/enums/ContractStatus.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/contract/service/ContractReader.java
  src/main/java/com/househub/backend/domain/contract/service/ContractService.java
  src/main/java/com/househub/backend/domain/contract/service/ContractStore.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractReaderImpl.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractStoreImpl.java
  src/main/java/com/househub/backend/domain/property/controller/PropertyController.java
  src/main/java/com/househub/backend/domain/property/dto/CreatePropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/property/dto/PropertySearchDto.java
  src/main/java/com/househub/backend/domain/property/dto/UpdatePropertyReqDto.java
  src/main/java/com/househub/backend/domain/property/entity/Property.java
  src/main/java/com/househub/backend/domain/property/enums/PropertyDirection.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepositoryCustom.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepositoryCustomImpl.java
  src/main/java/com/househub/backend/domain/property/service/PropertyReader.java
  src/main/java/com/househub/backend/domain/property/service/PropertyService.java
  src/main/java/com/househub/backend/domain/property/service/PropertyStore.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyReaderImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyStoreImpl.java
  src/test/java/com/househub/backend/domain/contract/service/ContractServiceTest.java
  src/test/java/com/househub/backend/domain/property/service/PropertyServiceTest.java
Labels: Refactor

#147 youngseok, feat: 전송 실패 문자 재전송 로직 배치로 구현
  build.gradle
  compose.yaml
  src/main/java/com/househub/backend/HouseHubBackendApplication.java
  src/main/java/com/househub/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/househub/backend/common/exception/SmsSendFailException.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsReqDto.java
  src/main/java/com/househub/backend/domain/sms/entity/Sms.java
  src/main/java/com/househub/backend/domain/sms/enums/SmsStatus.java
  src/main/java/com/househub/backend/domain/sms/job/SmsJobScheduler.java
  src/main/java/com/househub/backend/domain/sms/job/SmsResendJobConfig.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/service/SmsExecutor.java
  src/main/java/com/househub/backend/domain/sms/service/SmsReader.java
  src/main/java/com/househub/backend/domain/sms/service/SmsStore.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsExecutorImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsReaderImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsStoreImpl.java
Labels: Feature

#149 전국 지역 데이터 기반 지역 목록 조회 API 구현
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/domain/region/controller/RegionController.java
  src/main/java/com/househub/backend/domain/region/dto/RegionOptionDto.java
  src/main/java/com/househub/backend/domain/region/entity/Region.java
  src/main/java/com/househub/backend/domain/region/repository/RegionRepository.java
  src/main/java/com/househub/backend/domain/region/service/RegionCsvImportService.java
  src/main/java/com/househub/backend/domain/region/service/RegionReadService.java
Labels: Feature

#152 youngseok, feat: 고객 상세 페이지 상담/계약/문의 내역 추가
  .gitignore
  compose.yaml
  src/main/java/com/househub/backend/domain/consultation/repository/ConsultationRepository.java
  src/main/java/com/househub/backend/domain/consultation/service/ConsultationService.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
  src/main/java/com/househub/backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/househub/backend/domain/contract/service/ContractReader.java
  src/main/java/com/househub/backend/domain/contract/service/ContractService.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractReaderImpl.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerExecutor.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/inquiry/repository/InquiryRepository.java
  src/main/java/com/househub/backend/domain/inquiry/service/InquiryReader.java
  src/main/java/com/househub/backend/domain/inquiry/service/InquiryService.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryReaderImpl.java
  src/main/java/com/househub/backend/domain/inquiry/service/impl/InquiryServiceImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/repository/InquiryTemplateRepository.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/repository/QuestionRepository.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/property/repository/PropertyRepository.java
  src/main/java/com/househub/backend/domain/property/service/PropertyReader.java
  src/main/java/com/househub/backend/domain/property/service/PropertyService.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyReaderImpl.java
  src/main/java/com/househub/backend/domain/property/service/impl/PropertyServiceImpl.java
Labels: Feature

#157 고객&문자 목록에서 번호로 검색 시 - 추가 한 경우도 처리 가능 + 고객 가입시 생년월일 입력 + 엑셀 파일 입력 시 오류 메세지에 행 정보 추가
  src/main/java/com/househub/backend/common/validation/AgeGroupValidator.java
  src/main/java/com/househub/backend/common/validation/BirthDateAdultValidator.java
  src/main/java/com/househub/backend/common/validation/CustomerExcelValidator.java
  src/main/java/com/househub/backend/common/validation/ValidAgeGroup.java
  src/main/java/com/househub/backend/common/validation/ValidBirthDate.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CreateCustomerResDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/enums/CustomerExcelColumn.java
  src/main/java/com/househub/backend/domain/customer/job/CustomerBirthdayJobConfig.java
  src/main/java/com/househub/backend/domain/customer/job/CustomerContractExpireJobConfig.java
  src/main/java/com/househub/backend/domain/customer/job/CustomerJobScheduler.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepository.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepositoryCustom.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepositoryCustomImpl.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerExecutor.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerReader.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerStore.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/customer/util/CustomerExcelProcessor.java
  src/main/java/com/househub/backend/domain/sms/controller/SmsController.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsResDto.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/service/SmsExecutor.java
  src/main/java/com/househub/backend/domain/sms/service/SmsReader.java
  src/main/java/com/househub/backend/domain/sms/service/SmsService.java
  src/main/java/com/househub/backend/domain/sms/service/impl/AligoServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsExecutorImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsReaderImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsServiceImpl.java
  src/main/resources/templates/excel_template.xlsx
  src/test/java/com/househub/backend/domain/consultation/service/ConsultationServiceTest.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerReaderImplTest.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerStoreImplTest.java
Labels: Feature

#159 문의 템플릿 API 리팩토링 및 제목, 유형 수정 금지 및 정보 수정 시 새로운 템플릿 추가
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/common/validation/QuestionTypeValidator.java
  src/main/java/com/househub/backend/domain/auth/controller/AuthController.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/entity/CustomerCandidate.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerCandidateRepository.java
  src/main/java/com/househub/backend/domain/inquiry/dto/CreateInquiryReqDto.java
  src/main/java/com/househub/backend/domain/inquiry/entity/InquiryAnswer.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/controller/InquiryTemplateController.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/CreateInquiryTemplateReqDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/InquiryQuestionResDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/InquiryTemplatePreviewResDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/InquiryTemplateResDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/InquiryTemplateSearchCommand.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/QuestionDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/dto/UpdateInquiryTemplateReqDto.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/entity/InquiryTemplate.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/entity/InquiryTemplateSharedToken.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/entity/Question.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/enums/InquiryType.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/enums/QuestionType.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/repository/InquiryTemplateRepository.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/repository/InquiryTemplateSharedTokenRepository.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/repository/QuestionRepository.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateCreateExecutor.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateReader.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateService.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/InquiryTemplateStore.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateCreateExecutorImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateReaderImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateServiceImpl.java
  src/main/java/com/househub/backend/domain/inquiryTemplate/service/impl/InquiryTemplateStoreImpl.java
  src/main/java/com/househub/backend/domain/notification/service/EmailService.java
Labels: Feature

#164 byungchan, feature: 상담 등록 및 수정 정책 변경에 따른 상담 등록 및 수정 API 개선 #162
  src/main/java/com/househub/backend/common/config/WebSecurityConfig.java
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationReqDto.java
  src/main/java/com/househub/backend/domain/consultation/dto/UpdateConsultationReqDto.java
  src/main/java/com/househub/backend/domain/consultation/entity/Consultation.java
  src/main/java/com/househub/backend/domain/consultation/enums/ConsultationType.java
  src/main/java/com/househub/backend/domain/consultation/service/ConsultationService.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
Labels: Feature

#170 youngseok, fix: 고객 복구 기능 구현+ 삭제된 고객만 반환하도록 수정 + dto 정리 #165
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerListResDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerResDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepositoryCustom.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepositoryCustomImpl.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerExecutor.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerStore.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/customer/util/CustomerExcelProcessor.java
  src/main/java/com/househub/backend/domain/inquiry/dto/CreateInquiryReqDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerReaderImplTest.java
Labels: Feature, Refactor

#174 내부/외부 테스트 전 2차 배포
  src/main/java/com/househub/backend/common/exception/ErrorCode.java
  src/main/java/com/househub/backend/domain/contract/dto/ContractSearchDto.java
  src/main/java/com/househub/backend/domain/contract/dto/CreateContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/dto/FindContractResDto.java
  src/main/java/com/househub/backend/domain/contract/dto/UpdateContractReqDto.java
  src/main/java/com/househub/backend/domain/contract/entity/Contract.java
  src/main/java/com/househub/backend/domain/contract/service/impl/ContractServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/controller/CustomerController.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerListResDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerReqDto.java
  src/main/java/com/househub/backend/domain/customer/dto/CustomerResDto.java
  src/main/java/com/househub/backend/domain/customer/entity/Customer.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepositoryCustom.java
  src/main/java/com/househub/backend/domain/customer/repository/CustomerRepositoryCustomImpl.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerExecutor.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerService.java
  src/main/java/com/househub/backend/domain/customer/service/CustomerStore.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerExecutorImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerReaderImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerServiceImpl.java
  src/main/java/com/househub/backend/domain/customer/service/impl/CustomerStoreImpl.java
  src/main/java/com/househub/backend/domain/customer/util/CustomerExcelProcessor.java
  src/main/java/com/househub/backend/domain/inquiry/dto/CreateInquiryReqDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyDetailResDto.java
  src/main/java/com/househub/backend/domain/property/dto/FindPropertyResDto.java
  src/main/java/com/househub/backend/domain/sms/controller/SmsController.java
  src/main/java/com/househub/backend/domain/sms/dto/SendSmsResDto.java
  src/main/java/com/househub/backend/domain/sms/dto/SmsTypeCountDto.java
  src/main/java/com/househub/backend/domain/sms/repository/SmsRepository.java
  src/main/java/com/househub/backend/domain/sms/service/SmsReader.java
  src/main/java/com/househub/backend/domain/sms/service/SmsService.java
  src/main/java/com/househub/backend/domain/sms/service/impl/AligoServiceImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsReaderImpl.java
  src/main/java/com/househub/backend/domain/sms/service/impl/SmsServiceImpl.java
  src/test/java/com/househub/backend/domain/customer/service/CustomerReaderImplTest.java
Labels: Chore

#181 회원가입/로그인 및 신규 고객에 대한 상담 등록 버그 해결
  src/main/java/com/househub/backend/domain/auth/dto/SignUpReqDto.java
  src/main/java/com/househub/backend/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/househub/backend/domain/consultation/controller/ConsultationController.java
  src/main/java/com/househub/backend/domain/consultation/dto/ConsultationReqDto.java
  src/main/java/com/househub/backend/domain/consultation/service/impl/ConsultationServiceImpl.java
Labels: Bug
